### ISSUE TITLE
Fails to install into VS2012 or VS2013 due to MPF 14.0 dependency

### ISSUE THREAD

**Issue by RichieHindle** [Coverity-RnD/PresentationMode#1]
Installing into VS2015 works; 2012 and 2013 fail with:

---------------------------
VSIX Installer
---------------------------
This extension cannot be installed because the following references are missing:
- Visual Studio MPF 14.0

**Comment by sharwell** [comment]
Thanks for reporting this. I meant to remove that line during the update but forgot. I'll get it taken care of now! :smile:

**Comment by RichieHindle** [comment]
Great stuff!  Many thanks.

(And thanks for being such a helpful presence on the net for those of us attempting to create Visual Studio extensions!)
