### ISSUE TITLE
Exception from VS2013 Pro

### ISSUE THREAD

**Issue by RichieHindle** [Coverity-RnD/PresentationMode#4]
When you fire the Increase or Decrease commands in VS2013 Pro, you get an exception:

> Could not find the key in the registry (Exception from HRESULT: 0x80040152 (REGDB_E_KEYMISSING))

I've debugged this, and it's being thrown by this line:

    ErrorHandler.ThrowOnFailure(storage.GetFont(pLOGFONT, pInfo));

for the CodeLens category.  CodeLens isn't a feature of VS2013 Pro, so I guess that's the problem.  As a test, I changed that line to this:

    // This will fail if the category is not present, eg. CodeLens in VS2013 Pro.
    if (storage.GetFont(pLOGFONT, pInfo) == VSConstants.S_OK)
    {

and it all works perfectly.

**Comment by sharwell** [comment]
> I've debugged this,

How was this experience? I intended it to be very easy to clone this project and run it yourself. Did it actually turn out that way?

**Comment by sharwell** [comment]
This is very interesting. I would have thought the error would occur in the call to `OpenCategory`, but it sounds like that isn't the case.

**Comment by RichieHindle** [comment]
Yes, it was very easy.

The only thing that was a slight pain was due a limitation of Visual Studio - the project opens in VS 2015 as you'd expect, but the bug only fires in VS2013 and there's no mechanism (that I'm aware of?) to automatically deploy the VSIX into a different VS version for debugging.  Easily fixed by copying the output files into the appropriate VS2013 Extensions directory.

(Yes, I was surprised that the OpenCategory() call succeeded, but it did.)

**Comment by sharwell** [comment]
> there's no mechanism (that I'm aware of?) to automatically deploy the VSIX into a different VS version for debugging

Not only is there a way, but it's already enabled for this project. During a build within VS 2015, you should see lines in the output window about deploying to 2012 and 2013 (if you have on or both of them installed). Just edit the debug setting to change "14.0" to "12.0" in the path to devenv.exe.

**Comment by RichieHindle** [comment]
> Not only is there a way, but it's already enabled for this project.

:-)  Fantastic!  My apologies for simply assuming that this wouldn't work.  That will come in very handy!

**Comment by sharwell** [comment]
> :-) Fantastic! My apologies for simply assuming that this wouldn't work. That will come in very handy!

Note that this was a [very new development](https://twitter.com/samharwell/status/606284997469691904).

**Comment by sharwell** [comment]
By the way, I released *another* update to the extension with this fix. Hopefully all is right with the world now. :smile:

**Comment by RichieHindle** [comment]
Yes - 1.0.2 downloaded from the Gallery, tested in 2012 Pro, 2013 Pro and VS 2015 Pro, all working, no errors.  Thanks!

**Comment by sharwell** [comment]
Thank *you*. If you hadn't taken the time to report these back, it would still be broken for everyone! :smile:
